port: 4000

db:
  uri: 'sample'

auth:
  jwt:
    expires:
      access: '15m'
      refresh: '14d'
  cookie:
    name:
      access: '_cyat'
      refresh: '_cyrt'
    maxAge: 1_209_600_000 # 14d

upload:
  maxSize: 1_048_576 # 10mb
  maxFiles: 1
  path:
    upload: '/image/v2.0/appkeys/{appKey}/images'
  allowNamespaces: ["skill", "post"]